### ISSUE TITLE
无法打开输入文件“..\lib\Release\DXCam.lib”	screenshot

### ISSUE THREAD

**Issue by Xpropel** [Fidelxyz/DXCam-CPP#1]
When I want to run this example,I got this issue. I want to know if there is no this .lib file?

**Comment by Fidelxyz** [comment]
Did you compile this library first to get the binary `.lib` file? It should be in `/lib` in the output directory.

**Comment by Xpropel** [comment]
Firstly, I am very appreciated for your timely response! But, sorry, I couldn't find it in build/lib, and I also found a new issue this morning. It's decribed as internal compiler error. Detailedly, `错误	C1001	内部编译器错误。	DXCam	E:\c+test\DXCam-new\DXCam-CPP-main\src\util\io.cpp	54	`. I am so sorry for I am not experienced in C++.

**Comment by Fidelxyz** [comment]
It seems that the DXCam library is not properly built since `DXCam.lib` does not output.

Could you provide more details on how you build the library? Or you can try these:

- `cmake.exe -DCMAKE_BUILD_TYPE=Release "-DCMAKE_MAKE_PROGRAM=ninja.exe" "-DCMAKE_C_COMPILER=cl.exe" "-DCMAKE_CXX_COMPILER=cl.exe" -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_C_COMPILER_WORKS=1 -G Ninja -B ./build/`
- `cmake.exe --build .\build\ --target DXCam`

About "Fatal Error C1001", I think it is an issue relative to MSVC. Someone said disabling compiler optimization may work (you can try `-DCMAKE_BUILD_TYPE=Debug` in the first command), but it is not a long-term solution. Anyway, you can try the above solution and see if it occurs again.

**Comment by Xpropel** [comment]
I am grateful to get your response again. I think I hava got the method to solve this problem. Thank you very munch!!!  Your are so excellent ！

**Comment by Fidelxyz** [comment]
You're welcome. Thanks for using my project :)
