### ISSUE TITLE
Some small question about OpenCV

### ISSUE THREAD

**Issue by Mika4334** [Fidelxyz/DXCam-CPP#3]
why you implement OpenCV I do not get it? I just feel like it will slow everything. если вдруг разговариваешь на русском можешь ответить не на английском?

**Comment by Fidelxyz** [comment]
I don't think OpenCV will slow down the program much. Here is the profiling result on a benchmark.

<img width="428" alt="image" src="https://github.com/Fidelxyz/DXCam-CPP/assets/32995107/00cff02c-c821-428d-8084-e826f8065aa4">

In some cases, this library uses OpenCV for some frame post-processing (like rotation and color conversion). The implementation in OpenCV is already fast (with the existence of plenty optimization e.g. SIMD).

The main reason using OpenCV here is: in practice you're not just only grabbing a frame, but also processing that image, and probably you will use OpenCV to do that (since it may be the most popular C++ image processing library). So why don't we just return frames in the OpenCV format?
